var dataList = [
  ["Headdress", false, 1],
  ["No.4 Uniform", false, 1],
  ["Combat boots", false, 1],
  ["Towel", false, 1],
  ["Admin shirt", false, 1],
  ["PT Shorts", false, 1],
  ["Undergarments", false, 2],
  ["Socks", false, 2],
  ["Foot Powder", false, 1],
  ["Toilet Paper roll", false, 1],
  ["Soap Sponge", false, 1],
  ["Toothpaste", false, 1],
  ["Toothbrush", false, 1],
  ["Shaving Kit", false, 1],
  ["‘C’ size spare batteries", false, 2],
  ["Boot laces", false, 1],
  ["Garters", false, 1],
  ["Candles", false, 6],
  ["Lighter", false, 1],
  ["Sewing Kit", false, 1],
  ["Sandals", false, 1],
  ["Helmet", false, 1],
  ["Fork and Spoon", false, 1],
  ["Insect repellent", false, 1],
  ["Black Tape", false, 1],
  ["Range Card", false, 1],
  ["Marker set", false, 1],
  ["Fire sticks", false, 2]
];
